---
language: node_js

node_js:
  - node
  - 14
  - 12
  - 10

stages:
  - lint
  - test
  - name: deploy
    if: |
      branch = master AND
      env(NPM_TOKEN) IS present AND
      type NOT IN (pull_request)

install:
  - npm ci

jobs:
  include:
    - stage: lint
      script:
        - npm run lint
    - stage: test
      script:
        - npm test
      after_success:
        - npm run coverage
    - stage: deploy
      before_script:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
      script:
        - skip
      deploy:
        skip_cleanup: true
        provider: script
        script: npm publish
        on:
          condition: $(git describe --exact-match HEAD 2>/dev/null)
